# Primary colors
foreground               #dad4bb
background               #504d44

# Cursor colors
cursor #cecacd
cursor_text_color #0e0b1c

# Selection colors
selection_foreground     #4e4b42 
selection_background     #c2bca5

# # Normal colors
# color0  #1a162b
# color1  #ff7b89
# color2  #8fffa2
# color3  #f5d37c
# color4  #6aa9ff
# color5  #b58cff
# color6  #6cf0ff
# color7  #d0d0ff
#
# # Bright colors
# color8  #2c2560
# color9  #ff92a0
# color10 #9fffb3
# color11 #ffe599
# color12 #8bb8ff
# color13 #cba4ff
# color14 #8cf7ff
# color15 #f0f0ff
