-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TODO: manual review: preload = "/home/fuyuki/Pictures/wallpapers/lain.jpg"

-- TODO: manual review: wallpaper = "", "/home/fuyuki/Pictures/wallpapers/lain.jpg"

-- TODO: manual review: wallpaper = "DP-2", "/home/fuyuki/Pictures/wallpapers/lain.gif"
